## 1.Indexing and Slicing Vector ndarrays

### 1-1.Indexing

In [1]:
import numpy as np

a = np.arange(6)
print(f'ndarray:\n{a}\n')

print(f'a[0]: {a[0]}')
print(f'a[3]: {a[3]}')
print(f'a[-1]: {a[-1]}')
print(f'a[-3]: {a[-3]}\n')

# 리스트와 동일하게 for문 사용가능
for data in a:
    print(data)

ndarray:
[0 1 2 3 4 5]

a[0]: 0
a[3]: 3
a[-1]: 5
a[-3]: 3

0
1
2
3
4
5


### 1-2.Slicing

In [2]:
import numpy as np

a = np.arange(10)
print(f'ndarray:\n{a}\n')

print(f'a[0:3]: {a[0:3]}')
print(f'a[3:7]: {a[3:7]}')
print(f'a[5:-1]: {a[5:-1]}\n')

print(f'a[2:]: {a[2:]}')
print(f'a[-2:]: {a[-2:]}\n') # 마지막 2개의 원소

print(f'a[:5]: {a[:5]}')
print(f'a[:-3]: {a[:-3]}')
print(f'a[:]: {a[:]}\n')

print(f'a[2:7:2]: {a[2:7:2]}')
print(f'a[::3]: {a[::3]}')
print(f'a[7:2:-1]: {a[7:2:-1]}')
print(f'a[::-1]: {a[::-1]}')
print(f'a[8:3:-2]: {a[8:3:-2]}')
print(f'a[::-3]: {a[::-3]}\n')

print(f'a[[0,3,6,-1]]: {a[[0,3,6,-1]]}')
print(f'a[a%3==0]: {a[a%3==0]}')

ndarray:
[0 1 2 3 4 5 6 7 8 9]

a[0:3]: [0 1 2]
a[3:7]: [3 4 5 6]
a[5:-1]: [5 6 7 8]

a[2:]: [2 3 4 5 6 7 8 9]
a[-2:]: [8 9]

a[:5]: [0 1 2 3 4]
a[:-3]: [0 1 2 3 4 5 6]
a[:]: [0 1 2 3 4 5 6 7 8 9]

a[2:7:2]: [2 4 6]
a[::3]: [0 3 6 9]
a[7:2:-1]: [7 6 5 4 3]
a[::-1]: [9 8 7 6 5 4 3 2 1 0]
a[8:3:-2]: [8 6 4]
a[::-3]: [9 6 3 0]

a[[0,3,6,-1]]: [0 3 6 9]
a[a%3==0]: [0 3 6 9]


In [3]:
import numpy as np

a = np.arange(1, 11)
print(f'ndarray:\n{a}\n')

a[:5] = 0
print(f'ndarray:\n{a}\n')

a[[6,8]] = 100
print(f'ndarray:\n{a}\n')

a[::2] = 200
print(f'ndarray:\n{a}\n')

a[5:-1:3] = 55
print(f'ndarray:\n{a}')

ndarray:
[ 1  2  3  4  5  6  7  8  9 10]

ndarray:
[ 0  0  0  0  0  6  7  8  9 10]

ndarray:
[  0   0   0   0   0   6 100   8 100  10]

ndarray:
[200   0 200   0 200   6 200   8 200  10]

ndarray:
[200   0 200   0 200  55 200   8  55  10]


## 2.Indexing and Slicing Matrix ndarrays

In [4]:
import numpy as np

a = np.arange(12).reshape((3,4))
print(f'ndarray:\n{a}\n')

print(f'a[0]: {a[0]}')
print(f'a[1]: {a[1]}')
print(f'a[2]: {a[2]}\n')

print(f'a[0,0], a[0,1], a[0,2]: {a[0,0], a[0,1], a[0,2], a[0,3]}')
print(f'a[1,0], a[1,1], a[1,2]: {a[1,0], a[1,1], a[1,2], a[1,3]}')
print(f'a[2,0], a[2,1], a[2,2]: {a[2,0], a[2,1], a[2,2], a[2,3]}\n')

print(f'a[0,2:]: {a[0,2:]}')
print(f'a[1,:3]: {a[1,:3]}')
print(f'a[2,1:3]: {a[2,1:3]}\n')

print(f'a[1:,0]: {a[1:,0]}')
print(f'a[:3,1]: {a[:2,1]}')
print(f'a[1:3,2]: {a[1:3,2]}')

ndarray:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a[0]: [0 1 2 3]
a[1]: [4 5 6 7]
a[2]: [ 8  9 10 11]

a[0,0], a[0,1], a[0,2]: (0, 1, 2, 3)
a[1,0], a[1,1], a[1,2]: (4, 5, 6, 7)
a[2,0], a[2,1], a[2,2]: (8, 9, 10, 11)

a[0,2:]: [2 3]
a[1,:3]: [4 5 6]
a[2,1:3]: [ 9 10]

a[1:,0]: [4 8]
a[:3,1]: [1 5]
a[1:3,2]: [ 6 10]


In [5]:
import numpy as np

a = np.arange(16).reshape((4,4))
print(f'ndarray:\n{a}\n')

print(f'a[1:3,1:3]:\n{a[1:3,1:3]}\n')
print(f'a[:2,:3]:\n{a[:2,:3]}\n')
print(f'a[-3:,-2:]:\n{a[-3:,-2:]}\n')
print(f'a[2:,:-2]:\n{a[2:,:-2]}')

ndarray:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

a[1:3,1:3]:
[[ 5  6]
 [ 9 10]]

a[:2,:3]:
[[0 1 2]
 [4 5 6]]

a[-3:,-2:]:
[[ 6  7]
 [10 11]
 [14 15]]

a[2:,:-2]:
[[ 8  9]
 [12 13]]


In [6]:
import numpy as np

image = np.arange(9).reshape((3,3))
print(f'ndarray:\n{image}\n')

horizontal_flip = image[:, ::-1]
print(f'horizontal_flip:\n{horizontal_flip}\n')

vertical_flip = image[::-1, :]
print(f'vertical_flip:\n{vertical_flip}\n')

rotation = image[::-1, ::-1]
print(f'rotation:\n{rotation}')

ndarray:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

horizontal_flip:
[[2 1 0]
 [5 4 3]
 [8 7 6]]

vertical_flip:
[[6 7 8]
 [3 4 5]
 [0 1 2]]

rotation:
[[8 7 6]
 [5 4 3]
 [2 1 0]]


In [7]:
import numpy as np

a = np.arange(16).reshape((4,4))
print(f'ndarray:\n{a}\n')

print(f'a[0, :]: {a[0, :]}') # 해당 차원을 모두 가져옴
print(f'a[0, ...]: {a[0,...]}\n') # 나머지 차원을 모두 가져옴

print(f'a[:, 1]: {a[:, 1]}')
print(f'a[..., 1]: {a[..., 1]}')

ndarray:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

a[0, :]: [0 1 2 3]
a[0, ...]: [0 1 2 3]

a[:, 1]: [ 1  5  9 13]
a[..., 1]: [ 1  5  9 13]


## 3.Indexing and Slicing 3rd Order Tensor ndarrays

In [8]:
import numpy as np

a = np.arange(27).reshape((3,3,3))
print(f'ndarray:\n{a}\n')

print(f'a[0]:\n{a[0]}')
print(f'a[1]:\n{a[1]}')
print(f'a[2]:\n{a[2]}\n')

print(f'a[0,0]: {a[0,0]}')
print(f'a[0,1]: {a[0,1]}')
print(f'a[0,2]: {a[0,2]}')
print(f'a[1,0]: {a[1,0]}')
print(f'a[1,1]: {a[1,1]}')
print(f'a[1,2]: {a[1,2]}')
print(f'a[2,0]: {a[2,0]}')
print(f'a[2,1]: {a[2,1]}')
print(f'a[2,2]: {a[2,2]}\n')

print(f'a[0,:2,:2]:\n{a[0,:2,:2]}')
print(f'a[1,:2]:\n{a[1,:2]}')
print(f'a[2,-2:,-2:]:\n{a[2,-2:,-2:]}')

ndarray:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

a[0]:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
a[1]:
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
a[2]:
[[18 19 20]
 [21 22 23]
 [24 25 26]]

a[0,0]: [0 1 2]
a[0,1]: [3 4 5]
a[0,2]: [6 7 8]
a[1,0]: [ 9 10 11]
a[1,1]: [12 13 14]
a[1,2]: [15 16 17]
a[2,0]: [18 19 20]
a[2,1]: [21 22 23]
a[2,2]: [24 25 26]

a[0,:2,:2]:
[[0 1]
 [3 4]]
a[1,:2]:
[[ 9 10 11]
 [12 13 14]]
a[2,-2:,-2:]:
[[22 23]
 [25 26]]


In [9]:
import numpy as np

images = np.random.normal(size=(32, 100, 200))
print(f'image set: {images.shape}\n')

print(f'images[0,:,:].shape: {images[0,:,:].shape}')
print(f'images[0,...].shape: {images[0,...].shape}\n')

print(f'images[:,:,0].shape: {images[:,:,0].shape}')
print(f'images[...,0].shape: {images[...,0].shape}\n')

print(f'images[0,:,0].shape: {images[0,:,0].shape}')
print(f'images[0,...,0].shape: {images[0,...,0].shape}')

image set: (32, 100, 200)

images[0,:,:].shape: (100, 200)
images[0,...].shape: (100, 200)

images[:,:,0].shape: (32, 100)
images[...,0].shape: (32, 100)

images[0,:,0].shape: (100,)
images[0,...,0].shape: (100,)


In [10]:
import numpy as np

a = np.arange(27).reshape((3,3,3))
print(f'ndarray:\n{a}\n')

print(f'a[:,:2,:]:\n{a[:,:2,:]}\n')

print(f'a[:,:,0]:\n{a[:,:,0]}\n')

print(f'a[1:,-2:,-2:]:\n{a[1:,-2:,-2:]}')

ndarray:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

a[:,:2,:]:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]

a[:,:,0]:
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]

a[1:,-2:,-2:]:
[[[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]


In [11]:
import numpy as np

image  = np.random.normal(size=(3,500,300))

image_r, image_g, image_b = image   # using unpacking

print(f'image_r.shape: {image_r.shape}')
print(f'image_g.shape: {image_g.shape}')
print(f'image_b.shape: {image_b.shape}\n')

top_left = image[:, :100, :100]
top_right = image[:, :100, -100:]
bottom_left = image[:, -100:, :100]
bottom_right = image[:, -100:, -100:]

print(f'top_left.shape: {top_left.shape}')
print(f'top_right.shape: {top_right.shape}')
print(f'bottom_left.shape: {bottom_left.shape}')
print(f'bottom_right.shape: {bottom_right.shape}')

image_r.shape: (500, 300)
image_g.shape: (500, 300)
image_b.shape: (500, 300)

top_left.shape: (3, 100, 100)
top_right.shape: (3, 100, 100)
bottom_left.shape: (3, 100, 100)
bottom_right.shape: (3, 100, 100)


## 4.Indexing with int ndarrays

### 4-1.Indexing and Slicing Vector ndarrays

In [12]:
import numpy as np

a = np.arange(10)
print(f'ndarray:\n{a}\n')

print(f'a[[0,3,4]]: {a[[0,3,4]]}')
print(f'a[[0,0,5,5]]: {a[[0,0,5,5]]}\n')

indices = np.array([[1,2,3], [5,8,9]])
print(f'indices:\n{indices}')
print(f'a[indices]:\n{a[indices]}')

ndarray:
[0 1 2 3 4 5 6 7 8 9]

a[[0,3,4]]: [0 3 4]
a[[0,0,5,5]]: [0 0 5 5]

indices:
[[1 2 3]
 [5 8 9]]
a[indices]:
[[1 2 3]
 [5 8 9]]


In [13]:
import numpy as np

a = np.random.randint(0,20, (10,))
print(f'ndarray:\n{a}\n')

indices = np.random.randint(0,10, size=(2,3,4))
print(f'indices:\n{indices}')
print(f'a[indices]:\n{a[indices]}')

ndarray:
[ 0 12  1 13  3  5  1 17  0  4]

indices:
[[[5 0 0 4]
  [7 3 1 6]
  [6 3 4 7]]

 [[7 7 6 4]
  [3 6 9 0]
  [2 9 1 5]]]
a[indices]:
[[[ 5  0  0  3]
  [17 13 12  1]
  [ 1 13  3 17]]

 [[17 17  1  3]
  [13  1  4  0]
  [ 1  4 12  5]]]


### 4-2.Indexing and Slicing Matrix ndarrays

In [14]:
import numpy as np

a = np.arange(12).reshape((3,4))
print(f'nodarray: \n{a}\n')

indices= np.array([0,2])
print(f'indices:\n{indices}')
print(f'a[indices]:\n{a[indices]}\n')

indices = np.array([0,0,1,1,2,2])
print(f'indices:\n{indices}')
print(f'a[indices]:\n{a[indices]}\n')

indices = np.array([[0,1,2], [-3,-2,-1]])
print(f'indices:\n{indices}')
print(f'a[indices]:\n{a[indices]}\n')

indices0, indices1 = np.array([0,1,2]), np.array([1,2,3])
print('Paired indices:')
for idx0, idx1 in zip(indices0, indices1):
    print(f'{idx0, idx1}')
print(f'a[indices0, indices1]: {a[indices0, indices1]}')

indices0 = np.array([[0,1,2],[0,1,2]])
indices1= np.array([[0,1,2],[1,2,3]])
for row_indices0, row_indices1 in zip(indices0, indices1):
    for idx0, idx1 in zip(row_indices0, row_indices1):
        print(f'{idx0,idx1}',end=' ')
    print()
print(f'a[indices0, indices1]:\n{a[indices0, indices1]}')

nodarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices:
[0 2]
a[indices]:
[[ 0  1  2  3]
 [ 8  9 10 11]]

indices:
[0 0 1 1 2 2]
a[indices]:
[[ 0  1  2  3]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]]

indices:
[[ 0  1  2]
 [-3 -2 -1]]
a[indices]:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]

Paired indices:
(0, 1)
(1, 2)
(2, 3)
a[indices0, indices1]: [ 1  6 11]
(0, 0) (1, 1) (2, 2) 
(0, 1) (1, 2) (2, 3) 
a[indices0, indices1]:
[[ 0  5 10]
 [ 1  6 11]]


## 5.Indexing with bool ndarrays

### 5-1.Indexing and Slicing Vector ndarrays

In [15]:
import numpy as np

a = np.arange(5)
print(f'ndarray:\n{a}\n')

b_indices = np.array([True, False, True, False, True])
print(f'b_indices:\n{b_indices}')
print(f'a[b_indices]:\n{a[b_indices]}\n')

ndarray:
[0 1 2 3 4]

b_indices:
[ True False  True False  True]
a[b_indices]:
[0 2 4]



In [16]:
import numpy as np

a = np.random.randint(0,20, (10,))
print(f'ndarray:\n{a}\n')

b_indices = (a%2 == 0)
print(f'b_indices:\n{b_indices}')
print(f'a[b_indices]:\n{a[b_indices]}\n')

ndarray:
[ 4 11 15  4  1  5  1 17 16 19]

b_indices:
[ True False False  True False False False False  True False]
a[b_indices]:
[ 4  4 16]



### 5-2.Indexing and Slicing Matrix ndarrays

In [17]:
import numpy as np

a = np.random.randint(0,20, (2,2))
print(f'ndarray:\n{a}\n')

b_indices = np.array([[True, False],
                      [False, True]])
print(f'b_indices:\n{b_indices}')
print(f'a[b_indices]:\n{a[b_indices]}\n')

ndarray:
[[ 9  5]
 [ 4 12]]

b_indices:
[[ True False]
 [False  True]]
a[b_indices]:
[ 9 12]



In [18]:
import numpy as np

a = np.random.randint(0,20, (3,4))
print(f'ndarray:\n{a}\n')

b_indices = (a>10)
print(f'b_indices:\n{b_indices}')
print(f'a[b_indices]:\n{a[b_indices]}\n')

ndarray:
[[16 18 18 19]
 [ 5 13 12  8]
 [ 0 15 13  8]]

b_indices:
[[ True  True  True  True]
 [False  True  True False]
 [False  True  True False]]
a[b_indices]:
[16 18 18 19 13 12 15 13]



### 5-3.Extracting Indices

In [19]:
import numpy as np

a = np.array([True, False, True, False])

nonzero = np.nonzero(a)
where = np.where(a)
print(f'a:\n{a}')
print(f'nonzero:\n{nonzero}')
print(f'where:\n{where}\n')

a = np.array([[True,False],
              [True, False]])

nonzero = np.nonzero(a)
where = np.where(a)
print(f'a:\n{a}')
print(f'nonzero:\n{nonzero}')
print(f'where:\n{where}')

a = np.array([[[True, False, True],
              [True, False, False]],
              
              [[False, True, False],
               [True, False, True]]])

nonzero = np.nonzero(a)
where = np.where(a)
print(f'a:\n{a}\n')
print(f'nonzero:\n{nonzero}')
print(f'where:\n{where}')

a:
[ True False  True False]
nonzero:
(array([0, 2]),)
where:
(array([0, 2]),)

a:
[[ True False]
 [ True False]]
nonzero:
(array([0, 1]), array([0, 0]))
where:
(array([0, 1]), array([0, 0]))
a:
[[[ True False  True]
  [ True False False]]

 [[False  True False]
  [ True False  True]]]

nonzero:
(array([0, 0, 0, 1, 1, 1]), array([0, 0, 1, 0, 1, 1]), array([0, 2, 0, 1, 0, 2]))
where:
(array([0, 0, 0, 1, 1, 1]), array([0, 0, 1, 0, 1, 1]), array([0, 2, 0, 1, 0, 2]))


In [20]:
import numpy as np

a = np.random.randint(-2,3, size=(3,3))

u_nonzero = a[np.nonzero(a)]
u_where = a[np.where(a)]
u_bool = a[a != 0]

print(f'a:\n{a}\n')

print(f'using nonzero: \n{u_nonzero}')
print(f'using where: \n{u_where}')
print(f'using bool ndarray: \n{u_bool}\n')

u_nonzero = a[np.nonzero(a > 0)]
u_where = a[np.where(a > 0)]
u_bool = a[a > 0]

print(f'using nonzero: \n{u_nonzero}')
print(f'using where: \n{u_where}')
print(f'using bool ndarray: \n{u_bool}')

a:
[[-2  0 -2]
 [ 0  1  2]
 [ 0 -1 -2]]

using nonzero: 
[-2 -2  1  2 -1 -2]
using where: 
[-2 -2  1  2 -1 -2]
using bool ndarray: 
[-2 -2  1  2 -1 -2]

using nonzero: 
[1 2]
using where: 
[1 2]
using bool ndarray: 
[1 2]
