## 1.ndarray의 합곱차 구하기


### 1-1.summation
- np.cumsum(a, axis=None, dtype=None, out=None)
- ndarray.cumsum(a, axis=None, dtype=None, out=None)

In [1]:
import numpy as np

a = np.arange(5)
print(f'ndarray: {a}\n')

cumsum = np.cumsum(a)
print(f'cumsum: {cumsum}')

ndarray: [0 1 2 3 4]

cumsum: [ 0  1  3  6 10]


In [2]:
import numpy as np

a = np.arange(12).reshape((3,-1))
print(f'ndarray:\n{a}, shape: {a.shape}\n')

cumsum = np.cumsum(a)
print(f'cumsum:\n{cumsum}, shape: {cumsum.shape}\n')

cumsum = np.cumsum(a, axis=0)
print(f'cumsum(axis=0):\n{cumsum}, shape: {cumsum.shape}\n')

cumsum = np.cumsum(a, axis=1)
print(f'cumsum(axis=1):\n{cumsum}, shape: {cumsum.shape}')

ndarray:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape: (3, 4)

cumsum:
[ 0  1  3  6 10 15 21 28 36 45 55 66], shape: (12,)

cumsum(axis=0):
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]], shape: (3, 4)

cumsum(axis=1):
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]], shape: (3, 4)


### 1-2.Product
- np.prod(a, axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- np.cumprod(a ,axis=None, dtype=None, out=None)

In [3]:
import numpy as np

a = np.arange(1, 5)
print(f'ndarray: {a}\n')

prod = np.prod(a)
cumprod = np.cumprod(a)
print(f'prod: {prod}')
print(f'cumprod: {cumprod}, shape: {cumprod}')

ndarray: [1 2 3 4]

prod: 24
cumprod: [ 1  2  6 24], shape: [ 1  2  6 24]


In [4]:
import numpy as np

a = np.arange(1,13).reshape((3,-1))
print(f'ndarray:\n{a}, shape: {a.shape}\n')

prod = np.prod(a, axis=0)
cumprod = np.cumprod(a, axis=0)
print(f'prod(axis=0):\n{prod}, shape: {prod.shape}\n')
print(f'cumprod(axis=0):\n{cumprod}, shape: {cumprod.shape}\n')

prod = np.prod(a, axis=1, keepdims=True)
cumprod = np.cumprod(a, axis=1)
print(f'prod(axis=1, keepdims=True):\n{prod}, shape: {prod.shape}\n')
print(f'cumprod(axis=1):\n{cumprod}, shape: {cumprod.shape}')

ndarray:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape: (3, 4)

prod(axis=0):
[ 45 120 231 384], shape: (4,)

cumprod(axis=0):
[[  1   2   3   4]
 [  5  12  21  32]
 [ 45 120 231 384]], shape: (3, 4)

prod(axis=1, keepdims=True):
[[   24]
 [ 1680]
 [11880]], shape: (3, 1)

cumprod(axis=1):
[[    1     2     6    24]
 [    5    30   210  1680]
 [    9    90   990 11880]], shape: (3, 4)


### 1-3.Difference
- np.diff(a, n=1, axis=-1, prepend=no value, append=no value)

In [5]:
import numpy as np

a = np.random.randint(0,10,(5,))
print(f'ndarray:\n{a}, shape: {a.shape}\n')

diff = np.diff(a)
print(f'diff:\n{diff}, shape: {diff.shape}')

ndarray:
[0 7 4 3 4], shape: (5,)

diff:
[ 7 -3 -1  1], shape: (4,)


In [6]:
import numpy as np

a = np.random.randint (0,10,(4,4))
print(f'ndarray:\n{a}, shape: {a.shape}\n')

diff = np.diff(a, axis=0)
print(f'diff(axis=0):\n{diff}, shape: {diff.shape}\n')

diff = np.diff(a, axis=1)
print(f'diff(axis=1):\n{diff}, shape: {diff.shape}')

ndarray:
[[6 7 3 8]
 [9 6 9 1]
 [8 3 8 9]
 [1 4 9 7]], shape: (4, 4)

diff(axis=0):
[[ 3 -1  6 -7]
 [-1 -3 -1  8]
 [-7  1  1 -2]], shape: (3, 4)

diff(axis=1):
[[ 1 -4  5]
 [-3  3 -8]
 [-5  5  1]
 [ 3  5 -2]], shape: (4, 3)


## 2.ndarray의 통계값 구하기

### 2-1.Mean vs Average
- np.mean(a, axis=None, dtype=None, out=None, keepdims=no value, *, where=no value)
- ndarray.mean(axis=None, dtype=None, out=None, keepdims=no value, *, where=no value)

In [7]:
import numpy as np

x = np.random.randint(1,10,(5,))
w = np.array([1,2,3,4,5])
w = w/w.sum()
print(f'ndarry:\n{x}\n')

mean = np.mean(x)
print(f'mean: {np.mean(x)}\n')

print(f'weigths: {w}')
print(f'average: {np.average(x, weights=w)}')

print(f'np.sum(x*w): {np.sum(x*w)}')

ndarry:
[4 9 4 3 5]

mean: 5.0

weigths: [0.06666667 0.13333333 0.2        0.26666667 0.33333333]
average: 4.7333333333333325
np.sum(x*w): 4.7333333333333325


### 2-2.Median
np.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)

In [8]:
import numpy as np

x = np.arange(9)
median = np.median(x)
print(f'ndarray:\n{x}, median: {median}\n')

x = np.arange(10)
median = np.median(x)
print(f'ndarray:\n{x}, median: {median}')

ndarray:
[0 1 2 3 4 5 6 7 8], median: 4.0

ndarray:
[0 1 2 3 4 5 6 7 8 9], median: 4.5


In [9]:
import numpy as np

x = np.random.randint(1,10, (100,))
print(f'ndarry:\n{x}\n')

mean = np.mean(x)
median = np.median(x)
print(f'mean/median: {mean} / {median}\n')

x = np.append(x, 1000)
mean = np.mean(x)
median = np.median(x)
print(f'mean/median: {mean} / {median}') # mean은 outlier에 민감하여 커지는것을 볼수있다

ndarry:
[8 7 6 8 8 3 4 2 3 7 9 2 7 7 4 8 8 4 3 5 8 3 6 4 3 6 3 5 9 4 2 6 5 2 2 1 3
 3 4 9 1 3 3 2 2 3 2 7 9 6 6 9 6 1 4 3 4 2 7 8 2 4 6 5 5 3 2 7 8 9 4 8 3 7
 4 4 8 6 9 9 2 8 9 5 8 2 4 1 7 1 3 9 5 5 2 3 1 4 2 5]

mean/median: 4.88 / 4.0

mean/median: 14.732673267326733 / 4.0


### 2-3.Variance and Standard Deviation
- np.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *,where=no value)
- ndarray.var(axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *,where=no value)
- np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *,where=no value)
- ndarray.std(axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *,where=no value)

In [10]:
import numpy as np

scores = np.random.normal(10,5, (100,))

var = scores.var()
std = scores.std()

print(f'variance: {var}')
print(f'standard deviation: {std}')

variance: 26.57337280358977
standard deviation: 5.154936740988173


### 2-4.Standardization

In [11]:
import numpy as np

means = [50,60,70]
stds = [3,5,10]
n_student, n_class = 100, 3

scores = np.random.normal(loc=means, scale=stds,
                          size=(n_student,n_class))
scores = scores.astype(np.float32)


mean = np.mean(scores, axis=0)
std = np.std(scores, axis=0)
print(f'Shape of scores: {scores.shape}, dtype: {scores.dtype}')
print(f'Mean: {mean}, shape = {mean.shape}')
print(f'Std: {std}, shape = {std.shape}\n')

score_stdz = (scores - mean)/std
mean = np.mean(score_stdz, axis=0)
std = np.std(score_stdz, axis=0)
print(f'Shape of scores: {score_stdz.shape}')
print(f'Mean: {mean}, shape = {mean.shape}')
print(f'Std: {std}, shape = {std.shape}')

Shape of scores: (100, 3), dtype: float32
Mean: [49.548985 61.13584  69.31036 ], shape = (3,)
Std: [2.8224275 5.208972  8.359892 ], shape = (3,)

Shape of scores: (100, 3)
Mean: [-4.4763090e-07 -6.4730642e-07  2.0700693e-06], shape = (3,)
Std: [1.0000004 0.9999998 1.       ], shape = (3,)


### 2-5.Max Values and Indices
- np.amax(a, axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- ndarray.max(axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- np.argmax(a, axis=None, out=None)
- ndarray.argmax(axis=None, out=None)

In [12]:
import numpy as np

a = np.random.randint(0,100, (10,))
print(f'ndarray:\n{a}')

M = np.max(a)
M_idx = np.argmax(a)
print(f'M/M_idx: {M}/{M_idx}')

ndarray:
[ 2 25 30 74 90 66  7 40 67  0]
M/M_idx: 90/4


In [13]:
import numpy as np

means = [50,60,70]
stds = [3,5,10]
n_student, n_class = 100, 3

scores = np.random.normal(loc=means, scale=stds,
                          size=(n_student,n_class))
scores = scores.astype(np.float32)
print(f'Shape of scores: {scores.shape}, dtype: {scores.dtype}\n')

scores_max = np.max(scores, axis=0)
scores_max_idx = np.argmax(scores, axis=0)
print(f'max scores(axis=0): {scores_max}, shape: {scores_max.shape}')
print(f'max indices(axis=0): {scores_max_idx}, shape: {scores_max_idx.shape}\n')

scores_max = np.max(scores, axis=1)
scores_max_idx = np.argmax(scores, axis=1)
print(f'Shape of max scores(axis=1): {scores_max.shape}')
print(f'Shape of max indices(axis=1): {scores_max_idx.shape}')

Shape of scores: (100, 3), dtype: float32

max scores(axis=0): [56.500973 69.02812  90.48809 ], shape: (3,)
max indices(axis=0): [35 33  5], shape: (3,)

Shape of max scores(axis=1): (100,)
Shape of max indices(axis=1): (100,)


### 2-6.Min Values and Indices
- np.amin(a, axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- ndarray.min(axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- np.argmin(a, axis=None, out=None)
- ndarray.argmin(axis=None, out=None)

In [14]:
# Min-max Normalization
import numpy as np

means = [50,60,70]
stds = [3,5,10]
n_student, n_class = 100, 3

scores = np.random.normal(loc=means, scale=stds,
                          size=(n_student,n_class))
scores = scores.astype(np.float32)
print(f'Shape of scores: {scores.shape}, dtype:{scores.dtype}')

M = np.max(scores, axis=0)
m = np.min(scores, axis=0)
print(f'max values: {M}, shape: {M.shape}')
print(f'min values: {m}, shape: {m.shape}\n')

score_nor = (scores - m)/(M-m)
print(f'Shape of Normalization: {score_nor.shape}')
M = np.max(score_nor, axis=0)
m = np.min(score_nor, axis=0)
print(f'Max Values: {M}, shape: {M.shape}')
print(f'min Values: {m}, shape: {m.shape}')

Shape of scores: (100, 3), dtype:float32
max values: [57.71766 72.99219 98.17157], shape: (3,)
min values: [43.909023 44.77567  39.79753 ], shape: (3,)

Shape of Normalization: (100, 3)
Max Values: [1. 1. 1.], shape: (3,)
min Values: [0. 0. 0.], shape: (3,)


### 2-7.Maximun and Minimum

In [15]:
import numpy as np

u = np.random.randint(0,10, (10,))
v = np.random.randint(0,10, (10,))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

maximum = np.maximum(u, v)
print(f'maximum: {maximum}, shape: {maximum.shape}')
minimum = np.minimum(u, v)
print(f'minimum: {minimum}, shape: {minimum.shape}')

u:
[9 6 6 6 3 9 2 3 8 1], shape: (10,)
v:
[4 9 8 7 0 0 7 4 3 1], shape: (10,)

maximum: [9 9 8 7 3 9 7 4 8 1], shape: (10,)
minimum: [4 6 6 6 0 0 2 3 3 1], shape: (10,)


In [16]:
import numpy as np

u = np.random.randint(0,10, (3,4))
v = np.random.randint(0,10, (3,4))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

maximum = np.maximum(u, v)
print(f'maximum:\n{maximum}, shape: {maximum.shape}')
minimum = np.minimum(u, v)
print(f'minimum:\n{minimum}, shape: {minimum.shape}')

u:
[[6 0 3 8]
 [6 5 3 0]
 [5 7 9 7]], shape: (3, 4)
v:
[[0 9 2 7]
 [0 1 6 6]
 [5 2 6 7]], shape: (3, 4)

maximum:
[[6 9 3 8]
 [6 5 6 6]
 [5 7 9 7]], shape: (3, 4)
minimum:
[[0 0 2 7]
 [0 1 3 0]
 [5 2 6 7]], shape: (3, 4)


In [17]:
import numpy as np

u = np.random.randint(0,10, (10,))
v = np.random.randint(0,10, (10,))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

maximum = np.zeros_like(u)
maximum[u >= v] = u[u >= v]
maximum[v > u] = v[v > u]
print(f'maximum:\n{maximum}, shape: {maximum.shape}')

minimum = np.zeros_like(u)
minimum[u <= v] = u[u <= v]
minimum[v < u] = v[v < u]
print(f'minimum:\n{minimum}, shape: {minimum.shape}')

u:
[3 1 8 4 5 3 5 5 9 6], shape: (10,)
v:
[8 7 2 8 3 3 1 6 6 9], shape: (10,)

maximum:
[8 7 8 8 5 3 5 6 9 9], shape: (10,)
minimum:
[3 1 2 4 3 3 1 5 6 6], shape: (10,)


In [18]:
import numpy as np

u = np.random.randint(0,10, (10,))
v = np.random.randint(0,10, (10,))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

# u가 더크면 100, v가 더 크면 -100
up_vals = np.full_like(u, fill_value=100)
down_vals = np.full_like(u, fill_value=-100)
print(np.where(u>v, up_vals, down_vals))

u:
[6 9 9 8 6 2 6 1 2 7], shape: (10,)
v:
[9 2 8 0 8 8 9 5 3 9], shape: (10,)

[-100  100  100  100 -100 -100 -100 -100 -100 -100]


In [19]:
import numpy as np

u = np.random.randint(0,10, (10,))
v = np.random.randint(0,10, (10,))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

maximum = np.maximum(u,v)
maximum_where = np.where(u>v,u,v)
print(f'maximum:\n{maximum}, shape: {maximum.shape}')
print(f'maximum(where): \n{maximum_where}, shape: {maximum_where.shape}\n')

minimum = np.minimum(u,v)
minimum_where = np.where(u<v,u,v)
print(f'minimum:\n{minimum}, shape: {minimum.shape}')
print(f'minimum(where): \n{minimum_where}, shape: {minimum_where.shape}')

u:
[2 8 2 0 0 2 2 0 2 0], shape: (10,)
v:
[4 2 2 0 1 9 2 5 7 5], shape: (10,)

maximum:
[4 8 2 0 1 9 2 5 7 5], shape: (10,)
maximum(where): 
[4 8 2 0 1 9 2 5 7 5], shape: (10,)

minimum:
[2 2 2 0 0 2 2 0 2 0], shape: (10,)
minimum(where): 
[2 2 2 0 0 2 2 0 2 0], shape: (10,)
